config:
  target: "http://localhost:4000"
  phases:
    - duration: 300
      arrivalRate: 10
      maxVusers: 50
      name: "Warm up"
scenarios:
  - name: "Testing users"
    flow:
      - post:
          url: "/login"
          json:
            login: "admin"
            password: "admin"
          capture:
            - json: "$.token"
              as: "token"
      - get:
          url: "/users"
          headers:
            authorization: "Bearer {{ token }}"
      - post:
          url: "/users"
          headers:
            authorization: "Bearer {{ token }}"
          json:
            name: "John Doe"
            login: "john"
            password: "123456"
          capture:
            - json: "$.id"
              as: "id"
      - get:
          url: "/users/{{ id }}"
          headers:
            authorization: "Bearer {{ token }}"
      - put:
          url: "/users/{{ id }}"
          headers:
            authorization: "Bearer {{ token }}"
          json:
            name: "Jane Doe"
            login: "jane"
            password: "654321"
      - delete:
          url: "/users/{{ id }}"
          headers:
            authorization: "Bearer {{ token }}"