version: '3'
services:
  app:
    image: odil/express-rest-service_app
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
    networks:
      - custom-network
    restart: on-failure
  postgres:
    image: odil/express-rest-service_postgres
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - ${PGPORT}:${PGPORT}
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - custom-network
    restart: on-failure
networks:
  custom-network:
    driver: bridge