version: '3'
services:
  express:
    image: odil/express-rest-service_express
    build:
      context: .
      dockerfile: express.Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
    networks:
      - custom-network
    restart: on-failure
  postgres:
    image: odil/express-rest-service_postgres
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - custom-network
    restart: on-failure
networks:
  custom-network:
    driver: bridge